---
- name: Add Users and Group
  hosts: all
 
  tasks:
   - name: Add group "nixadmins" to remote server
     group:
       name: nixadmins
       gid: 2010
       state: present

   - name: Add group "Office" to remote server
     group:
       name: office
       gid: 2011
       state: present
